### ISSUE TITLE
大佬，麻烦把viptypeVersion相关的都改成long类型吧，网易应该改了API了，不改会崩溃

### ISSUE THREAD

**Issue by dayfan0810** [kalac2232/Hearing#1]

**Comment by dayfan0810** [comment]
private long viptypeVersion;

        public long getViptypeVersion() {
            return viptypeVersion;
        }

**Comment by kalac2232** [comment]
> ```
>     private long viptypeVersion;
> 
>     public long getViptypeVersion() {
>         return viptypeVersion;
>     }
> ```

老铁 问题提错地方了吧
